service: sls-user-profile
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: '20201221'
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
    TABLE_NAME: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::${self:custom.bucketName}/*
        - arn:aws:s3:::${self:custom.bucketName}
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  excludeDevDependencies: true

custom:
  esbuild:
    bundle: true
    minify: false
  bucketName: ${opt:stage, 'dev'}-mvc-user-profile
  tableName: ${opt:stage, 'dev'}-users-profile

functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - http:
          path: /user-profile
          method: POST
          cors: true
