service: sls-user-profile
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: '20201221'
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
    TABLE_NAME: ${self:custom.tableName}
    SNS_USER_CREATED_TOPIC: ${self:custom.snsUserProfileCreatedArn}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::${self:custom.bucketName}/*
        - arn:aws:s3:::${self:custom.bucketName}
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        - ${self:custom.snsUserProfileCreatedArn}

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  excludeDevDependencies: true

custom:
  esbuild:
    bundle: true
    minify: false
    tsconfig: tsconfig-build.json
  bucketName: ${opt:stage, 'dev'}-mvc-user-profile
  tableName: ${opt:stage, 'dev'}-users-profile
  snsUserProfileCreatedArn: arn:aws:sns:${aws:region}:${aws:accountId}:${opt:stage, 'dev'}-user-profile-created
  sqsUserProfileCreatedArn: arn:aws:sqs:${aws:region}:${aws:accountId}:${opt:stage, 'dev'}-user-profile-created-queue
functions:
  create-user:
    handler: src/main/handlers/create-user.handler
    events:
      - http:
          path: /user-profile
          method: POST
          cors: true
  user-profile:
    handler: src/main/handlers/user-profile.handler
    events:
      - sqs:
          arn: ${self:custom.sqsUserProfileCreatedArn}
          batchSize: 1
